name: Test Robaho Http Server

on:
  push:
  pull_request:

jobs:
  run-lein-tests:
    name: Lein test
    uses: ruroru/workflows/.github/workflows/lein-test.yaml@master
    with:
      lein_test_profile: 'robaho'